
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form anasayfa
     */
    public anasayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        neredentxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nereyetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ayGidis3 = new javax.swing.JComboBox<>();
        gunGidis3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        neredentxt.setForeground(new java.awt.Color(102, 102, 102));
        neredentxt.setText("sehir giriniz");
        jPanel1.add(neredentxt);
        neredentxt.setBounds(60, 410, 170, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 228, 63));
        jLabel2.setText("nereden");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 370, 100, 29);

        nereyetxt.setForeground(new java.awt.Color(102, 102, 102));
        nereyetxt.setText("sehir giriniz");
        jPanel1.add(nereyetxt);
        nereyetxt.setBounds(290, 410, 170, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 228, 63));
        jLabel3.setText("nereye");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 370, 120, 22);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        ayGidis3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ay", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        gunGidis3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gun", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gunGidis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(ayGidis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayGidis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gunGidis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(510, 410, 126, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("ARA");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 500, 65, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
        jLabel4.setText("ÖZ PAÜ JET ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 720, 116);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("TURİZM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 110, 110, 28);

        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Yönetci Giris");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1350, 666, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ucak-bileti.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, -4, 1540, 780);

        jMenu1.setText("Kaydol");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Profilim");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String[] colNames = {"sehirKalkis","sehirGidis","havalimaniKalkis","havalimaniGidis","seferNo","gun","ay","saat","koltuklar"};
        String[][] data;

        Connection con=proje.getConnection();
        PreparedStatement ps;
        Statement st =null;
        try {
            //    "select * from ucak where concat ('sehirKalkis','sehirGidis','havalimaniKalkis','havalimaniGidis') like '%"+nerdentxt.getText()+"%'"
            //            ps=con.prepareStatement("select * from ucak where sehirGidis like '%"+nerdentxt.getText()+"%'");
            //            String url="select * from ucak where sehirGidis like '%" +nerdentxt.getText()+ "%'";
            //
            ps=con.prepareStatement("select * from ucak where sehirKalkis like '%" +neredentxt.getText()+ "%' and sehirGidis like '%" +nereyetxt.getText()+ "%'");
            String url="select * from ucak where  sehirKalkis  like '%" +neredentxt.getText()+ "%' and sehirGidis like '%" +nereyetxt.getText()+ "%'";
            System.out.println(url);
            st=con.createStatement();
            ResultSet rs= st.executeQuery(url);

            rs.last();
            int count = rs.getRow();
            data = new String[count][colNames.length];
            rs.beforeFirst();
            int i = 0;
            rezervasyontablo a=new rezervasyontablo();
            while(rs.next())
            {
                data[i][0] = rs.getString("sehirKalkis");
                data[i][1] = rs.getString("sehirGidis");
                data[i][2] = rs.getString("havalimaniKalkis");
                data[i][3] = rs.getString("havalimaniGidis");
                data[i][4] = rs.getString("seferNo");
                data[i][5] = rs.getString("gun");
                data[i][6] = rs.getString("ay");
                data[i][7] = rs.getString("saat");
                data[i][8] = rs.getString("koltuklar");

                i++;

                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                this.dispose();

            }
            DefaultTableModel model = new DefaultTableModel(data,colNames);
            a.displaytable.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        rezervasyontablo a=new rezervasyontablo();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ayGidis3;
    private javax.swing.JComboBox<String> gunGidis3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField neredentxt;
    private javax.swing.JTextField nereyetxt;
    // End of variables declaration//GEN-END:variables
}
